on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dummy hello world
        run: echo Hello World!
      - name: Test for build
        run: 
          npm i
          npm run build
          nodemon index.js
      - name: Generate Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifact01
          path: ./artifacts
      - name: Artifacts step done!
        run: echo Artifacts uploaded

    
    
