on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dummy hello world
        run: echo Hello World!
      - name: Set up node_env
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Test for build
        run: 
          npm ci
          npm run build
          nodemon index.js
      - name: Make a dir for atrifacts
        run: mkdir artifacts
      - name: Generate Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifact01
          path: dist/
      - name: Artifacts step done!
        run: echo Artifacts uploaded

    
    
